spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: web_user
    url: jdbc:mariadb://192.168.2.129:3306/myDB
    password: '1234'
  profiles:
    active: prod
server:
  port: '11000'